config/routes.rb
Admission::Application.routes.draw do
 
  devise_for :users

  match "campaigns/:campaign_id/records/new" => "records#create", via: :post 
  match "campaigns/:campaign_id/records/:record_id/edit" => "records#update", via: :post
  resources :record_types
  resources :campaigns do
    resources :records
  end

  match "campaigns/:campaign_id/edit/records" => "campaigns#modify_records", via: :put

  root to:"campaigns#index"

end

app/models/campaign.rb
# -*- encoding : utf-8 -*-
class Campaign < ActiveRecord::Base
	attr_accessible :description, :name, :records, :record_type_id
	has_and_belongs_to_many :records
	has_and_belongs_to_many :sp_container, class_name:"Record", join_table: :sp_records
	has_and_belongs_to_many :cn_container, class_name:"Record", join_table: :cn_records

	def to_csv
		csv = CSV.generate( :quote_char => "\0") do |csv|
			array = ""
			
			records.first.attributes.each_key do |key|
				array << key.to_s + "," unless key =~ /properties/
			end

			records.first.attributes["properties"].each_key do |key|
				array << key.to_s + ","	
			end

			array = array[0..array.length-2].chomp
			
			csv << [array.strip]

			self.records.each do |record|
				array = ""
				record.attributes.each do |key, value|
					array << value.to_s + "," unless key =~ /properties/
				end
				record.attributes["properties"].each do |key,value|
					array << value.to_s + ","
				end

				array = array[0..array.length-2].chomp
			
				csv << [array]
			end
		end
		csv.gsub!(/\0/, '')
	end
	
	def bal_aligment 
	    records_array = self.records.all
	    records_array.each do |r|
	      if !r.properties.key? :bal
	        r.calculate_bal
	        r.save
	      end
	      r.properties["bal"] = r.properties["bal"].to_f
	    end

	    records_array.sort_by {|r| r.properties[:bal]}.reverse
 	end

 	def specialties_alignment
 		records_array = bal_aligment
 		puts "============================ #{records_array.size} ==================================="
 		while (sp_container.size < 29 || cn_container.size < 29 ) && !records_array.empty? do
	 		records_array.each do |r|
	 			if r.properties["Желание1".to_sym].to_i == 1 && sp_container.size < 29
	 				puts "------------------------------- Vliza v Jelanie 1 sp ---------------------------"
	 				sp_container<< r
	 				records_array.delete_if {|x| x == r}
	 			elsif r.properties["Желание1".to_sym].to_i == 2 && cn_container.size < 29
	 				puts "------------------------------- Vliza v Jelanie 1 cn ---------------------------"
	 				cn_container<< r
	 				records_array.delete_if {|x| x == r}
	 			elsif r.properties["Желание2".to_sym].to_i == 1 && sp_container.size < 29
	 				puts "------------------------------- Vliza v Jelanie 2 sp ---------------------------"
	 				sp_container<< r
	 				records_array.delete_if {|x| x == r}
	 			elsif r.properties["Желание2".to_sym].to_i == 2 && cn_container.size < 29
	 				puts "------------------------------- Vliza v Jelanie 2 cn ---------------------------"
	 				cn_container<< r
	 				records_array.delete_if {|x| x == r}
	 			end
	 		end
 		end
 		self.save	
 	end


end


# SP = 1 / CN = 2

app/controllers/campaigns_controller.rb
# -*- encoding : utf-8 -*-
class CampaignsController < ApplicationController

  before_filter :authenticate_user!

  def index
    @campaigns = Campaign.all 
  end

  def new
    @campaign = Campaign.new
    @record_types = []
    RecordType.all.each { |rt| @record_types<< [rt.name,rt.id]}

  end

  def create
    @campaign = Campaign.new(params[:campaign])
    if @campaign.save
      render status: :ok 
    else
      flash[:alert] = "Грешка при създаването на кампанията. Моля опитайте отново"
      render "campaigns#new"
    end
  end

  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy
  end

  def edit
    @campaign = Campaign.find(params[:id])
  end

  def show
    if params[:id].nil?
      @campaign = Campaign.last
    else  
      @campaign = Campaign.find(params[:id])
    end

    if @campaign.nil?
      @campaign = Campaign.new
      @record_types = RecordType.all
      render "new"
    end

    respond_to do |format|
      format.html
      format.csv {send_data @campaign.to_csv}
      format.xls
    end
  end

  def update
    @campaign = Campaign.find(params[:id])

    if @campaign.update_attributes(params[:campaign])
      flash[:success] = "Кампанията бе успешно обновлена"
      redirect_to @campaign
    else
      flash[:alert] = "Кампанията не бе успешно обновлена. Моля опитайте отново"
    end
  end

  def modify_records
    params[:record_ids].each do |id|
      Record.find(id).destroy
    end
    redirect_to Campaign.find(params[:campaign_id])
  end

  # def search 
  #   records = Record.search params[:search]
  #   respond_to do |format|
  #    if records.nil? || records.empty?
  #    format.html {redirect_to :back, notice: "Нищо не беше открито" }
  #     else
  #    format.html {render "search_result"}
  #    end
  #   end
  # end
  
end

app/helpers/campaigns_helper.rb
# -*- encoding : utf-8 -*-
module CampaignsHelper



  def bal_aligment campaign
    records_array = campaign.records.all
    records_array.each do |r|
      if !r.properties.key? :bal
        r.calculate_bal
        r.save
      end
      r.properties["bal"] = r.properties["bal"].to_f
    end

    records_array.sort_by {|r| r.properties[:bal]}.reverse
  end


  def specialty_aligment 
  	records_array = bla_aligment
  end
end

app/views/campaigns/create.html.erb
<%= link_to "Всички кампании", root_url + "campaigns/"%>

app/views/campaigns/destroy.html.erb
<h1>Campaigns#destroy</h1>
<p>Find me in app/views/campaigns/destroy.html.erb</p>

app/views/campaigns/edit.html.erb
<%= render "campaigns/new.html.erb"%>

app/views/campaigns/index.html.erb
<table class="table table-striped">
	<thead>
		<th>Име</th>
		<th>Описание</th>
	</thead>
	<% @campaigns.each do |c| %>
		<tr>
			<td><%= c.name %></td>
			<td><%= c.description %></td>
			<td><%= link_to "Повече информация", root_url + "campaigns/#{c.id}", :class => "btn btn-primary" %></td>
		</tr>
	<% end %>
</table>

<%= link_to "Нова кампания", root_url + "campaigns/new", :class => "btn btn-primary"%>

app/views/campaigns/new.html.erb
<% if ! @record_types.empty? %>
	<div class = "well well-small">
	<div class="form-body">
	<%= form_for @campaign do |f| %>
		<div class="panel panel-primary", id ="n-camp-pan">
		<ul>
			<li>
				Име:<br>
				<div class="form-group">
				<%= f.text_field :name, :class => "form-control" %>
				</div>
			</li>
			<li>
				Описание:<br> 
				<div class="form-group">
				<%= f.text_area :description, :rows => "10", :class =>"form-control"%>
				</div>
			</li>	
			<li>
				Тип на записите:<br> 
				<div class="form-group">
				<%= f.select :record_type_id, 
					@record_types, :class => "form-control"
				%>
				</div>
			</li>
		</ul>
		<%= f.submit "Запиши", :class => "btn btn-primary" %>
		</div>
		</div>
	<% end %>
	<div class="panel panel-footer">
		<%= link_to "Всички Кампании",root_url+"campaigns/", :class => "btn btn-primary "%>
	</div>
	</div>
<%else%>
	<p>
		За да създадете нова кампания трябва да сте създали поне един вид на записи. <br>
		Цъкнете линка, за да го направите.
	</p>
	<%=
		link_to "Създай нов вид запис",
		root_url + "record_types/new"
	%>
<%end%>

app/views/campaigns/show.html.erb
<div id="content">
	<%= form_for @campaign, url: {action: 'modify_records', campaign_id: @campaign.id} do |f| %>

	<section id="actions">
		<ul>
			<li><%= link_to raw('<i class="icon-plus-sign"></i> Нов кандидат'), new_campaign_record_path(campaign_id: @campaign.id, record_type_id: @campaign.record_type_id)%></li>
			<li><%= link_to "Всички Кампании", root_url + "campaigns/"%></li>
			<li><%= link_to "Генерирай csv файл", root_url + "campaigns/#{@campaign.id}.csv"%></li>
			<li><%= link_to "Генерирай xls файл", root_url + "campaigns/#{@campaign.id}.xls"%></li>
		</ul>
	</section>

	<table id="campaign-records">
		<thead>
			<tr>
				<th><input type="checkbox" id="checkAll" /></th>
				<th>ID</th>
				<%if !@campaign.records.first.nil?%>
					<% @campaign.records.first.properties.each_key do |property|%>
						<%if (property =~ /Бащино име/)|| 
							(property =~ /Собствено име/) || 
							(property =~ /Фамилно име/) ||
							(property =~ /EГН/) ||
							(property =~ /БЕЛ - училище/) ||
							(property =~ /Физика - училище/) ||
							(property =~ /Математика - изпит/) ||
							(property =~ /Български - изпит/) ||
							(property =~ /Математика - ТУЕС/) ||
							(property =~ /Желание1/) ||
							(property =~ /Желание2/)
						%>
							<th><%=property%></th>
						<% end %>
					<% end %>
				<% end %>
				<!--<th>Профил</th>-->
				<th>Повече</th>
			</tr>
		</thead>
		<tbody>
			<% @campaign.records.each do |record| %>
			<tr>
				<td><%= check_box_tag 'record_ids[]', record.id %></td>
				<td><%= record.entry_number %> </td>
			
				<% record.properties.each do |key,value| %>
					<%if (key =~ /Бащино име/)|| 
							(key =~ /Собствено име/) || 
							(key =~ /Фамилно име/) ||
							(key =~ /EГН/) ||
							(key =~ /БЕЛ - училище/) ||
							(key =~ /Физика - училище/) ||
							(key =~ /Математика - изпит/) ||
							(key =~ /Български - изпит/) ||
							(key =~ /Математика - ТУЕС/) ||
							(key =~ /Желание1/) ||
							(key =~ /Желание2/)
						%>
							<th><%=value%></th>
						<% end %>
				<% end %>
				<!--<td class="center"><%= link_to raw('<i class="icon-user"></i>'), campaign_record_path(campaign_id: @campaign.id, id: record.id), method: :get %></td>-->
				<td><%= link_to "Повече информация", root_url + "campaigns/#{record.campaign_id}/records/#{record.id}", :class => "btn btn-primary" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<% end %>
</div>

app/views/campaigns/show.xls.erb
<html>
<head>
	<title>@campaign.name</title>
	<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
</head>
<body>
	<table>
		<thead>
			<td>Record ID</td>
			<% @campaign.records.first.properties.each_key do |propertie|%>
			<td><%= propertie %></td>
			<% end %>
		</thead>
		<tbody>
			<% @campaign.records.each do |record| %>
			<tr>
				<td><%= record.id %> </td>
				<% record.properties.each_value do |value| %>
				<td><%= value %></td>
				<% end %>
			</tr>
			<% end %>
		</tbody>
	</table>
</body>
</html>